src/pathme_viewer/web/views.py
# -*- coding: utf-8 -*-

"""This module contains the PathMe views."""

import datetime
import logging
import sys
from operator import itemgetter

from flask import (
    Blueprint,
    abort,
    current_app,
    jsonify,
    render_template,
    request
)
from flask_admin.contrib.sqla import ModelView
from networkx import NetworkXNoPath, all_simple_paths, betweenness_centrality, shortest_path
from pkg_resources import resource_filename
from pybel import from_bytes
from pybel.struct import get_random_path
from pybel.struct.mutation.collapse import collapse_to_genes
from pybel.struct.mutation.induction import get_subgraph_by_annotations

from pathme_viewer.constants import (
    COLLAPSE_TO_GENES,
    DATABASE_STYLE_DICT,
    DATABASE_URL_DICT,
    PATHS_METHOD,
    RANDOM_PATH,
    UNDIRECTED
)
from pathme_viewer.graph_utils import (
    export_graph,
    get_annotations_from_request,
    get_tree_annotations,
    merge_pathways,
    prepare_venn_diagram_data,
    process_request,
    process_overlap_for_venn_diagram
)
from pathme_viewer.models import Pathway

log = logging.getLogger(__name__)
time_instantiated = str(datetime.datetime.now())

pathme = Blueprint(
    'pathme_viewer',
    __name__,
    template_folder=resource_filename('pathme_viewer', 'templates'),
    static_folder=resource_filename('pathme_viewer', 'templates')
)

redirect = Blueprint(
    '',
    __name__,
    template_folder=resource_filename('pathme_viewer', 'templates'),
    static_folder=resource_filename('pathme_viewer', 'templates')
)


class PathwayView(ModelView):
    """Pathway view in Flask-admin."""

    column_searchable_list = (
        Pathway.name,
        Pathway.resource_name,
        Pathway.pathway_id,
        Pathway.created,
        Pathway.number_of_nodes,
        Pathway.number_of_edges,
        Pathway.version,
        Pathway.pybel_version,
        Pathway.contact,
        Pathway.authors,
        Pathway.description,
    )
    column_list = (
        Pathway.name,
        Pathway.resource_name,
        Pathway.pathway_id,
        Pathway.created,
        Pathway.number_of_nodes,
        Pathway.number_of_edges,
        Pathway.version,
        Pathway.pybel_version,
        Pathway.contact,
        Pathway.authors,
        Pathway.description,
    )


"""Redirection to home page"""


@redirect.route('/')
def home():
    """Redirect to PathMe page. Only used when PathMe is run independent from ComPath."""
    return render_template('home.html')


"""Views"""


@pathme.route('/pathme')
def home():
    """PathMe home page."""
    return render_template('home.html')


@pathme.route('/imprint')
def imprint():
    """Render the Imprint page."""
    return render_template('meta/imprint.html')


@pathme.route('/pathme/about')
def about():
    """Render About page. Only when is run independent from ComPath"""
    example_kegg = current_app.pathme_manager.get_pathway_by_id('hsa00010', 'kegg')
    example_reactome = current_app.pathme_manager.get_pathway_by_id('R-HSA-109581', 'reactome')
    example_wp = current_app.pathme_manager.get_pathway_by_id('WP100', 'wikipathways')
    metadata = [
        ('Python Version', sys.version),
        ('Deployed', time_instantiated),
        ('KEGG Version', example_kegg.created if example_kegg else ''),
        ('Reactome Version', example_reactome.created if example_reactome else ''),
        ('WikiPathways Version', example_wp.created if example_wp else ''),
    ]

    return render_template('meta/about.html', metadata=metadata)


@pathme.route('/tutorial')
def tutorial():
    """Render the tutorial page"""
    return render_template('meta/help.html')


@pathme.route('/admin/delete/pathways')
def delete_pathways():
    """Delete all pathways."""
    current_app.pathme_manager.delete_all_pathways()

    return jsonify(
        status=200,
        message='All Pathways have been deleted',
    )


@pathme.route('/pathway/node')
def get_pathways_with_node():
    """Return all pathways having a given node"""

    bel_nodes = request.args.getlist('node_selection[]')

    if not bel_nodes:
        abort(500, '"{}" is not a valid input for this input'.format(request.args))

    pathways = set()

    for pathway in current_app.pathme_manager.get_all_pathways():
        # Load networkX graph
        graph = from_bytes(pathway.blob)

        # Check if node is in the pathway
        for node in graph:

            if node.as_bel() not in bel_nodes:
                continue

            pathways.add(pathway)

    return render_template(
        'pathway_table.html',
        pathways=pathways,
        DATABASE_URL_DICT=DATABASE_URL_DICT,
        DATABASE_STYLE_DICT=DATABASE_STYLE_DICT
    )


@pathme.route('/pathway/overlap')
def calculate_overlap():
    """Return the overlap between different pathways in order to generate a Venn diagram."""
    pathways = process_request(request)

    if len(pathways) < 2:
        return abort(500, 'Only one pathway has been submitted!')

    pathway_data = prepare_venn_diagram_data(current_app.pathme_manager, pathways)

    processed_venn_diagram = process_overlap_for_venn_diagram(pathway_data)

    return render_template(
        'pathway_overlap.html',
        processed_venn_diagram=processed_venn_diagram,
        DATABASE_STYLE_DICT=DATABASE_STYLE_DICT
    )


@pathme.route('/pathme/viewer')
def viewer():
    """PathMe page."""
    pathways = process_request(request)

    # List of all pathway names
    pathway_id_to_name = {}
    pathway_display_names = {}
    pathway_id_to_display_name = {}
    pathway_to_resource = {}
    for pathway_id, resource in pathways.items():
        pathway = current_app.pathme_manager.get_pathway_by_id(pathway_id, resource)

        if not pathway:
            continue

        pathway_id_to_display_name[pathway_id] = pathway.display_name
        pathway_to_resource[pathway_id] = resource
        pathway_display_names[pathway.display_name] = pathway_id
        pathway_id_to_name[pathway_id] = pathway.name

    return render_template(
        'pathme_viewer.html',
        pathways=pathways,
        pathway_id_to_name=pathway_id_to_name,
        pathways_name='+'.join(
            '<a href="{}" target="_blank"> {}</a><div class="circle {}"></div>'.format(
                DATABASE_URL_DICT[pathway_to_resource[pathway_id]].format(pathway_id.strip('hsa')),
                pathway_name,
                pathway_id
            )
            for pathway_name, pathway_id in pathway_display_names.items()
        ),
        pathway_ids=list(pathways.keys()),
        DATABASE_STYLE_DICT=DATABASE_STYLE_DICT,
        DATABASE_URL_DICT=DATABASE_URL_DICT
    )


@pathme.route('/api/pathway/')
def get_network():
    """Build a graph from request and sends it in the given format."""
    pathways = process_request(request)

    graph = merge_pathways(pathways)

    annotations = get_annotations_from_request(request)

    if annotations:
        graph = get_subgraph_by_annotations(graph, annotations)

    if COLLAPSE_TO_GENES in request.args:
        collapse_to_genes(graph)

    log.info(
        'Exporting merged graph with {} nodes and {} edges'.format(graph.number_of_nodes(), graph.number_of_edges())
    )

    graph.name = 'Merged graph from {}'.format([pathway_name for pathway_name in pathways])
    graph.version = '0.0.0'

    return export_graph(graph, request.args.get('format'))


@pathme.route('/api/tree/')
def get_network_tree():
    """Build a graph and sends the annotation ready to be rendered in the tree."""
    pathways = process_request(request)

    graph = merge_pathways(pathways)

    annotations = get_annotations_from_request(request)

    if annotations:
        graph = get_subgraph_by_annotations(graph, annotations)

    if COLLAPSE_TO_GENES in request.args:
        collapse_to_genes(graph)

    # Return annotation in graph
    return jsonify(get_tree_annotations(graph))


@pathme.route('/api/pathway/paths')
def get_paths():
    """Return array of shortest/all paths given a source node and target node both belonging in the graph

    ---
    tags:
        - paths
        - pathway

    parameters:
      - name: pathways[]
        description: pathway resource/name pair
        required: true
        type: str

      - name: resources[]
        description: pathway resource/name pair
        required: true
        type: str

      - name: source_id
        description: The identifier of the source node
        required: true
        type: str

      - name: target_id
        description: The identifier of the target node
        required: true
        type: str

      - name: cutoff
        in: query
        description: The largest path length to keep
        required: true
        type: integer

      - name: undirected

      - name: paths_method
        in: path
        description: The method by which paths are generated - either just the shortest path, or all paths
        required: false
        default: shortest
        schema:
            type: string
            enum:
              - all
              - shortest
    """
    pathways = process_request(request)

    graph = merge_pathways(pathways)

    # Create hash to node info
    hash_to_node = {
        node.sha512: node
        for node in graph
    }

    source_id = request.args.get('source')
    if source_id is None:
        raise IndexError('Source missing from cache: %s', source_id)

    target_id = request.args.get('target')
    if target_id is None:
        raise IndexError('target is missing from cache: %s', target_id)

    method = request.args.get(PATHS_METHOD)
    undirected = UNDIRECTED in request.args
    cutoff = request.args.get('cutoff', default=7, type=int)

    source = hash_to_node.get(source_id)
    target = hash_to_node.get(target_id)

    if source not in graph or target not in graph:
        log.info('Source/target node not in network')
        log.info('Nodes in network: %s', graph.nodes())

src/pathme_viewer/templates/base.html
{% extends "bootstrap/base.html" %}

{% block styles %}
    {{ super() }}
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/logo/pathme-logo-100px.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/nav.css') }}">
{% endblock %}

{% block head %}
    {{ super() }}
    {{ fixes.ie8() }}
{% endblock %}

{% block navbar %}
    {{ super() }}
    {% include "pathme_nav.html" %}
{% endblock %}

src/pathme_viewer/templates/home.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/fixes.html" as fixes %}
{% import "bootstrap/utils.html" as util %}

{% block title %}PathMe{% endblock %}


{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css"
          href='https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css'/>
    <link rel="stylesheet" type="text/css"
          href='https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css'/>
    <link rel="stylesheet" type="text/css"
          href='https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.min.css'/>

    <style>
        /* Fuse dynamic field buttons */

        [data-role="dynamic-fields"] > .form-inline + .form-inline {
            margin-top: 0.5em;
        }

        [data-role="dynamic-fields"] > .form-inline [data-role="add"] {
            display: none;
        }

        [data-role="dynamic-fields"] > .form-inline:last-child [data-role="add"] {
            display: inline-block;
        }

        [data-role="dynamic-fields"] > .form-inline:last-child [data-role="remove"] {
            display: none;
        }

        .box {
            display: flex;
            align-items: center;
        }
    </style>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {% include "dependencies/common.html" %}
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.full.min.js"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/home_controller.js') }}"></script>
{% endblock %}

{% block content %}


    <div class="container" style="margin-top: 50px">
        {{ util.flashed_messages(dismissible=True, container=False) }}

        <div class="jumbotron">
            <div class="row">
                <div class="box">
                    <div class="col-lg-2 col-md-2 col-sm-2">
                        <img src="{{ url_for('static', filename='img/logo/pathme-logo-100px.png') }}"/>
                    </div>
                    <div class="col-lg-10 col-md-10 col-sm-10">
                        <h1>PathMe Viewer</h1>
                        <p>A web application to merge and explore mechanistic pathway knowledge.</p>
                        <p>See our <a href="{{ url_for('pathme_viewer.tutorial') }}">tutorial on how to get started.</a>
                        </p>
                    </div>
                </div>
            </div>

        </div>

        <div class="panel panel-default">
            <div class="panel-heading">Merge and Explore Pathways Across Multiple Databases</div>
            <div class="panel-body">
                <div>
                    <p>
                        Below, you can select multiple pathways from different databases. To choose a
                        pathway, first select a database and the autocompletion form will then guide you to find
                        pathways of interest to you. After pathways have been selected, click on the "Explore" button to
                        render the merged network corresponding to the selected pathways.
                    </p>

                    <p>
                           <span>Examples:
                            <a class="nounderline"
                               href="/pathme/viewer?resources[]=kegg&pathways[]=hsa04150&resources[]=wikipathways&pathways[]=WP1471&resources[]=reactome&pathways[]=R-HSA-165159&resources[]=reactome&pathways[]=R-HSA-380972&resources[]=reactome&pathways[]=R-HSA-165181&resources[]=reactome&pathways[]=R-HSA-166208">mTOR signaling pathway</a>,
                <a class="nounderline"
                   href="/pathme/viewer?resources[]=kegg&pathways[]=hsa04010&resources[]=wikipathways&pathways[]=WP382&resources[]=reactome&pathways[]=R-HSA-5683057&resources[]=reactome&pathways[]=R-HSA-112411&resources[]=reactome&pathways[]=R-HSA-110056&resources[]=reactome&pathways[]=R-HSA-5674135&resources[]=reactome&pathways[]=R-HSA-5674499&resources[]=reactome&pathways[]=R-HSA-5673000&resources[]=reactome&pathways[]=R-HSA-5658442&resources[]=reactome&pathways[]=R-HSA-5687128">MAPK signaling pathway</a>
                    </span>
                    </p>


                </div>
                <div>
                    <form id="pathway-form" method="get" action="/pathme/viewer">
                        <div data-role="dynamic-fields">
                            <div class="form-inline">
                                <div class="form-group">
                                    <label class="sr-only" for="pathway">Pathways</label>

                                    <select type="text" class="form-control" name="resources[]" id="select-1">

                                        <option value="kegg">KEGG</option>
                                        <option value="reactome">Reactome</option>
                                        <option value="wikipathways">WikiPathways</option>

                                        <input type="text" class="form-control" name="pathways[]" id="input-1"
                                               placeholder="Select the Pathway to compare"
                                               style=" min-width: 500px;">
                                    </select>
                                </div>
                                <button class="btn btn-danger" data-role="remove">
                                    <span class="glyphicon glyphicon-remove"></span>
                                </button>
                                <button class="btn btn-primary" data-role="add">
                                    <span class="glyphicon glyphicon-plus"></span>
                                </button>
                            </div>  <!-- /div.form-inline -->
                        </div> <!-- /div[data-role="dynamic-fields"] -->
                        <div class="text-center" style="margin-top: 20px; margin-bottom: 20px">
                            <input class="btn btn-primary btn-lg" value="Explore Pathways" type="submit">
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <form id="query-form" method="get" action="{{ url_for('pathme_viewer.get_pathways_with_node') }}">

            <div class="panel panel-default">
                <div class="panel-heading">Explore Pathways Containing a Given Set of Nodes
                </div>
                <div class="panel-body">
                    <p>
                        Below, you can select BEL nodes (e.g., genes, compounds, miRNAs, etc.) and explore which set of
                        pathways
                        contain them.
                    </p>
                    <p>
                           <span>Examples:
                            <a class="nounderline"
                               href="/pathway/node?node_selection[]=g(HGNC%3AMTOR)&node_selection[]=p(HGNC%3AMTOR)">MTOR (gene and protein)</a>,
                <a class="nounderline"
                   href="/pathway/node?node_selection[]=p(HGNC%3AMAPK1)&node_selection[]=g(HGNC%3AMAPK1)">MAPK1 (gene and protein)</a>
                    </span>
                    </p>

                </div>
                <div class="form-group form-horizontal" style="padding-bottom: 20px; margin-bottom: 20px;">
                    <div class="col-md-10">
                        <select style="width: 60%" multiple="multiple" name="node_selection[]"
                                id="node_selection"></select>
                    </div>
                </div>

                <div class="text-center" style="margin-top: 20px; margin-bottom: 20px">
                    <input class="btn btn-primary btn-lg" value="Explore Pathways" type="submit">
                </div>
            </div>
        </form>
    </div>
    {% include "meta/footer.html" %}
{% endblock %}

src/pathme_viewer/templates/pathme.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/fixes.html" as fixes %}
{% import "bootstrap/utils.html" as util %}

{% block title %}PathMe{% endblock %}


{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css"
          href='https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css'/>

    <style>
        /* Fuse dynamic field buttons */

        [data-role="dynamic-fields"] > .form-inline + .form-inline {
            margin-top: 0.5em;
        }

        [data-role="dynamic-fields"] > .form-inline [data-role="add"] {
            display: none;
        }

        [data-role="dynamic-fields"] > .form-inline:last-child [data-role="add"] {
            display: inline-block;
        }

        [data-role="dynamic-fields"] > .form-inline:last-child [data-role="remove"] {
            display: none;
        }


    </style>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {% include "dependencies/common.html" %}
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

    <script type="text/javascript" src="{{ url_for('static', filename='js/home_controller.js') }}"></script>
{% endblock %}

{% block content %}


    <div class="container" style="margin-top: 50px">
        {{ util.flashed_messages(dismissible=True, container=False) }}

        <div class="jumbotron">
            <h1>PathMe Viewer</h1>
            <p>A web application to merge and explore the mechanistic pathway knowledge.
            </p>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">Merge and Explore Pathways Across Multiple Databases</div>
            <div class="panel-body">
                <div>
                    <p>
                        Below, you can select multiple pathways from different databases. To choose a
                        pathway, first select a database and the autocompletion form will then guide you to find
                        pathways of interest to you. After pathways have been selected, click on the "Explore" button to
                        render the merged network corresponding to the selected pathways.
                    </p>

                </div>
                <div>
                    <form id="pathway-form" method="get" action="/pathme/viewer">
                        <div data-role="dynamic-fields">
                            <div class="form-inline">
                                <div class="form-group">
                                    <label class="sr-only" for="pathway">Pathways</label>

                                    <select type="text" class="form-control" name="resources[]" id="select-1">

                                        <option value="kegg">KEGG</option>
                                        <option value="reactome">Reactome</option>
                                        <option value="wikipathways">WikiPathways</option>

                                        <input type="text" class="form-control" name="pathways[]" id="input-1"
                                               placeholder="Select the Pathway to compare"
                                               style=" min-width: 500px;">
                                    </select>
                                </div>
                                <button class="btn btn-danger" data-role="remove">
                                    <span class="glyphicon glyphicon-remove"></span>
                                </button>
                                <button class="btn btn-primary" data-role="add">
                                    <span class="glyphicon glyphicon-plus"></span>
                                </button>
                            </div>  <!-- /div.form-inline -->
                        </div> <!-- /div[data-role="dynamic-fields"] -->
                        <div class="text-center" style="margin-top: 20px; margin-bottom: 20px">
                            <input class="btn btn-primary btn-lg" value="Explore" type="submit">
                        </div>
                    </form>
                </div>
            </div>
            <table id="info-table" class="table table-bordered table-hover table-responsive"></table>
        </div>
    </div>
    {% include "meta/pathme_footer.html" %}
{% endblock %}

src/pathme_viewer/templates/pathme_nav.html
<nav class="navbar navbar-static-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button aria-controls="navbar" aria-expanded="false" class="navbar-toggle collapsed"
                    data-target="#485848c5cd0b7dabdf24f858e4f3abbf21fdb984" data-toggle="collapse" type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('pathme_viewer.home') }}">
                <img alt="ComPath" src="{{ url_for('static', filename='img/logo/pathme-logo-100px.png') }}"></a>
        </div>
        <div class="navbar-collapse collapse" id="485848c5cd0b7dabdf24f858e4f3abbf21fdb984">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a class="dropdown-toggle nav-header" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Getting Started <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{{ url_for('pathme_viewer.about') }}">About</a>
                        </li>
                        <li>
                            <a class="nav-header" href="{{ url_for('pathme_viewer.imprint') }}">Imprint</a>
                        </li>
                        <li>
                            <a href="{{ url_for('pathme_viewer.tutorial') }}">Tutorial</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle nav-header" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">SCAI Resources <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a class="nav-header"
                               href="http://belief.scai.fraunhofer.de/BeliefDashboard">BELIEF</a></li>
                        <li><a class="nav-header" href="https://neurommsig.scai.fraunhofer.de/">NeuroMMSig</a></li>
                        <li><a class="nav-header" href="http://ptsd.scai.fraunhofer.de/">PTSDDB</a>
                        </li>
                        <li><a class="nav-header" href="https://bel-commons.scai.fraunhofer.de/">BEL Commons</a>
                        </li>
                        <li>
                            <a class="nav-header" href="http://academia.scaiview.com/academia/">SCAIView</a>
                        </li>
                        <li>
                            <a class="nav-header" href="http://epad.scai.fraunhofer.de/">Study Viewer</a>
                        </li>
                    </ul>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right no-collapse">
                <li>
                    <a id="nav-scai-logo"
                       href="https://www.scai.fraunhofer.de/en/business-research-areas/bioinformatics.html">
                        <img alt="Fraunhofer SCAI"
                             src="{{ url_for('static', filename='img/scai_logo.svg') }}">
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

src/pathme_viewer/templates/pathway_table.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/fixes.html" as fixes %}
{% import "bootstrap/utils.html" as util %}

{% block title %}PathMe{% endblock %}


{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css"
          href='https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css'/>
    <link rel="stylesheet" type="text/css"
          href='https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css'/>
    <link rel="stylesheet" type="text/css"
          href='https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.min.css'/>

    <style>
        /* Fuse dynamic field buttons */

        [data-role="dynamic-fields"] > .form-inline + .form-inline {
            margin-top: 0.5em;
        }

        [data-role="dynamic-fields"] > .form-inline [data-role="add"] {
            display: none;
        }

        [data-role="dynamic-fields"] > .form-inline:last-child [data-role="add"] {
            display: inline-block;
        }

        [data-role="dynamic-fields"] > .form-inline:last-child [data-role="remove"] {
            display: none;
        }


    </style>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {% include "dependencies/common.html" %}

    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.16/datatables.min.js"></script>

    <script>
        $(document).ready(function () {
            var table = $("#pathway-table").DataTable();

            // Clicks all buttons tables
            $('#selectAll').click(function (e) {

                var boolean = $(this).prop('checked');

                // For each table add a hidden input to the form with the checked boxes
                $.each(table.$('input'), function (index, input) {
                    input.checked = boolean;
                });
            });

            // Preprocess form before submiting
            var form = $('#query-form');
            form.submit(function () {
                // Modify inputs to follow same schema as main page
                $.each(table.$('input'), function (index, input) {
                    if (input.checked) {
                        pathwayInfo = input.value.split("|");

                        var newInput1 = $("<input>")
                            .attr("type", "hidden")
                            .attr("name", "pathways[]").val(pathwayInfo[0]);

                        form.append(newInput1);

                        var newInput2 = $("<input>")
                            .attr("type", "hidden")
                            .attr("name", "resources[]").val(pathwayInfo[1]);

                        form.append(newInput2);
                    }
                    //Remove input
                    input.remove()
                });

                // Submit form
                return true;
            });
        });
    </script>
{% endblock %}

{% block content %}


    <div class="container" style="margin-top: 50px">
        {{ util.flashed_messages(dismissible=True, container=False) }}

        <form id="query-form" method="get" action="{{ url_for('pathme_viewer.viewer') }}">

            <div class="panel panel-default">
                <div class="panel-heading">Select the Pathways to Explore
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <table class="table table-striped table-responsive" id="pathway-table">
                            <thead>
                            <tr>
                                <th><input type="checkbox" title="Select All Networks" id="selectAll"/></th>
                                <th>Pathway</th>
                                <th>Database</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for pathway in pathways %}
                                <tr>
                                    <td>
                                        <input type="checkbox" name="unused"
                                               value="{{ pathway.pathway_id }}|{{ pathway.resource_name }}"/>
                                    </td>
                                    <td>
                                        <a href="{{ DATABASE_URL_DICT[pathway.resource_name].format(pathway.pathway_id.strip('hsa')) }}"
                                           target="_blank">
                                            {{ pathway.name }}
                                        </a>
                                    </td>
                                    <td>{{ DATABASE_STYLE_DICT[pathway.resource_name] }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="text-center" style="margin-top: 20px; margin-bottom: 20px">
                    <input class="btn btn-primary btn-lg" value="Explore Pathways" type="submit">
                </div>
            </div>
        </form>
    </div>
    {% include "meta/footer.html" %}
{% endblock %}